name: Deploy Static Website to AWS S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAYFOD3NMDGOMAMWVA
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Upload to S3 bucket
        run: |
          aws s3 sync . s3://cicdforfitness
